#!/usr/bin/env bash
set -euo pipefail
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE ROLE "$APP_DB_USER" LOGIN PASSWORD '$APP_DB_PASSWORD';
  GRANT CONNECT ON DATABASE "$POSTGRES_DB" TO "$APP_DB_USER";
  GRANT USAGE ON SCHEMA public TO "$APP_DB_USER";
EOSQL
