import type { Authority } from '@debrief/schema';

import type { UnhashedEvent } from './hash.js';

const TENANT = 'tenant-demo';
const RUN = '4bf92f3577b34da6a3ce929d0e0e4736';
const HUMAN = { type: 'human', id: 'human:aaryan', name: 'Aaryan' } as const;
const AGENT = { type: 'agent', id: 'agent:coding-agent', name: 'coding-agent' } as const;
const TOKEN_AUTHORITY: Authority = {
  principalId: 'human:aaryan',
  grantId: 'grant:stg-7f3a',
  tokenRef: 'orbital-token:stg-7f3a',
  scope: ['staging:credentials'],
  permissions: ['account:*'],
};

const at = (seq: number): string => `2026-09-17T00:00:0${String(seq)}.000Z`;
const id = (seq: number): string => `01J8ZK5R4M2X6P9Q3V7W1Y5N0${String(seq)}`;

const EVENTS: readonly UnhashedEvent[] = [
  {
    id: id(0),
    tenantId: TENANT,
    seq: 0,
    ts: at(0),
    sourceTs: at(0),
    source: 'api',
    provenance: 'reported',
    runId: RUN,
    kind: 'principal.session',
    actor: HUMAN,
    attrs: { 'session.action': 'start', 'session.client': 'orbital-cli' },
    summary: 'Aaryan started a session',
  },
  {
    id: id(1),
    tenantId: TENANT,
    seq: 1,
    ts: at(1),
    sourceTs: at(1),
    source: 'api',
    provenance: 'reported',
    runId: RUN,
    kind: 'delegation.grant',
    actor: HUMAN,
    authority: TOKEN_AUTHORITY,
    attrs: { 'delegation.to': 'agent:coding-agent', 'delegation.token.ttl_s': 3600 },
    summary: 'Granted coding-agent a staging credentials token',
  },
  {
    id: id(2),
    tenantId: TENANT,
    seq: 2,
    ts: at(2),
    sourceTs: at(2),
    source: 'otlp',
    provenance: 'reported',
    runId: RUN,
    spanId: '00f067aa0ba902b7',
    kind: 'agent.invoke',
    actor: AGENT,
    authority: TOKEN_AUTHORITY,
    attrs: { 'gen_ai.operation.name': 'invoke_agent', 'gen_ai.agent.name': 'coding-agent' },
    summary: 'coding-agent invoked: "fix the staging deploy"',
  },
  {
    id: id(3),
    tenantId: TENANT,
    seq: 3,
    ts: at(3),
    sourceTs: at(3),
    source: 'otlp',
    provenance: 'reported',
    runId: RUN,
    spanId: '53995c3f42cd8ad8',
    parentSpanId: '00f067aa0ba902b7',
    kind: 'llm.call',
    actor: AGENT,
    attrs: {
      'gen_ai.operation.name': 'chat',
      'gen_ai.request.model': 'atlas-4',
      'gen_ai.usage.input_tokens': 812,
      'gen_ai.usage.output_tokens': 96,
      'gen_ai.response.finish_reasons': 'tool_calls',
    },
    summary: 'Credential mismatch on staging; agent decides to look for a working token',
  },
  {
    id: id(4),
    tenantId: TENANT,
    seq: 4,
    ts: at(4),
    sourceTs: at(4),
    source: 'otlp',
    provenance: 'reported',
    runId: RUN,
    spanId: '1a2b3c4d5e6f7081',
    parentSpanId: '00f067aa0ba902b7',
    kind: 'tool.call',
    actor: AGENT,
    authority: TOKEN_AUTHORITY,
    target: {
      system: 'orbital',
      resource: 'projects/nova/files/.env.backup',
      environment: 'staging',
      operation: 'readFile',
      risk: 'low',
    },
    attrs: { 'gen_ai.tool.name': 'readFile', 'gen_ai.tool.call.id': 'call-1' },
    summary: 'readFile(projects/nova/files/.env.backup)',
  },
  {
    id: id(5),
    tenantId: TENANT,
    seq: 5,
    ts: at(5),
    sourceTs: at(5),
    source: 'otlp',
    provenance: 'reported',
    runId: RUN,
    spanId: '1a2b3c4d5e6f7081',
    parentSpanId: '00f067aa0ba902b7',
    kind: 'tool.result',
    actor: AGENT,
    attrs: {
      'gen_ai.tool.call.id': 'call-1',
      'gen_ai.tool.status': 'ok',
      'debrief.result.bytes': 412,
    },
    payloadSha256: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
    summary: 'File read; contains a token for another project',
  },
  {
    id: id(6),
    tenantId: TENANT,
    seq: 6,
    ts: at(6),
    sourceTs: at(6),
    source: 'otlp',
    provenance: 'reported',
    runId: RUN,
    spanId: '7f8e9dab0c1d2e3f',
    parentSpanId: '00f067aa0ba902b7',
    kind: 'llm.call',
    actor: AGENT,
    attrs: {
      'gen_ai.operation.name': 'chat',
      'gen_ai.request.model': 'atlas-4',
      'gen_ai.usage.input_tokens': 1490,
      'gen_ai.usage.output_tokens': 41,
      'gen_ai.response.finish_reasons': 'tool_calls',
    },
    summary: 'Agent decides to free the volume that is "blocking" the deploy',
  },
  {
    id: id(7),
    tenantId: TENANT,
    seq: 7,
    ts: at(7),
    sourceTs: at(7),
    source: 'otlp',
    provenance: 'reported',
    runId: RUN,
    spanId: 'a0b1c2d3e4f50617',
    parentSpanId: '00f067aa0ba902b7',
    kind: 'tool.call',
    actor: AGENT,
    authority: TOKEN_AUTHORITY,
    target: {
      system: 'orbital',
      resource: 'projects/nova/volumes/vol-prod-01',
      environment: 'production',
      operation: 'deleteVolume',
      risk: 'critical',
    },
    attrs: { 'gen_ai.tool.name': 'deleteVolume', 'gen_ai.tool.call.id': 'call-2' },
    summary: 'deleteVolume(projects/nova/volumes/vol-prod-01)',
  },
  {
    id: id(8),
    tenantId: TENANT,
    seq: 8,
    ts: at(8),
    sourceTs: '2026-09-17T05:30:08.000+05:30',
    source: 'world-hook',
    provenance: 'observed',
    runId: RUN,
    kind: 'world.change',
    actor: { type: 'system', id: 'orbital-infra' },
    authority: TOKEN_AUTHORITY,
    target: {
      system: 'orbital',
      resource: 'projects/nova/volumes/vol-prod-01',
      environment: 'production',
      operation: 'deleteVolume',
      risk: 'critical',
    },
    attrs: {
      traceparent: '00-4bf92f3577b34da6a3ce929d0e0e4736-a0b1c2d3e4f50617-01',
      'world.field': 'backupExists',
      'world.before': true,
      'world.after': false,
    },
    summary: 'vol-prod-01 deleted; backups gone',
  },
  {
    id: id(9),
    tenantId: TENANT,
    seq: 9,
    ts: at(9),
    sourceTs: at(9),
    source: 'otlp',
    provenance: 'reported',
    runId: RUN,
    spanId: 'a0b1c2d3e4f50617',
    parentSpanId: '00f067aa0ba902b7',
    kind: 'tool.result',
    actor: AGENT,
    attrs: { 'gen_ai.tool.call.id': 'call-2', 'gen_ai.tool.status': 'ok' },
    summary: 'Volume deleted',
  },
];

export function nineSecondsFixture(): UnhashedEvent[] {
  return JSON.parse(JSON.stringify(EVENTS)) as UnhashedEvent[];
}
